EX = main

all: main.o queue.o utilities.o
	gcc mian.o utilitites.o queue.o -o main			

main.o: main.c queue.h utilities.h
	gcc c main.c

queue.o: queue.c queue.h
	gcc -c queue.c

utiltities.o : utilitites.c utilitites.h
	gcc -c utilitites.c

clean :
	rm -f *.o $(EX)